os: linux
language: python
jobs: 
  include:
    - name: ubuntu14
      dist: trusty
      python:
        - "3.6"
      install:
        - pip3 install -r requirements.txt
        - pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

    - name: ubuntu18
      dist: bionic
      python:
        - "3.6"
      install:
        - pip3 install -r requirements.txt
        - pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
script:
  - python3 test/test.py
